### ISSUE TITLE
Can not compile or build in UE5.2.1

### ISSUE THREAD

**Issue by benpomfrey** [AgentOttsel/JoyShockLibrary4Unreal#4]
Does this work on 5.2.1? After adding to the project, it no longer opens.

**Comment by AgentOttsel** [comment]
Hey there! Thanks for your question!
I was in UE5.4 when I started the development of this plugin, and haven't tested it in lower versions than that. Could you share what compilation errors you're getting?
